---
- name: install progress
  yum:
    name: postgresql-server
    state: latest

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

 # only run the next 2 tasks once!
 # - name: initilize postgres
 #   command: postgresql-setup initdb
 # - name: initilize postgres some more
 #   command: chkconfig postgresql on

- name: Check database initialization
  command: postgresql-check-db-dir /var/lib/pgsql/data
  register: check_db_output
  changed_when: check_db_output == 1
  ignore_errors: yes

- name: initialize postgres
  shell: postgresql-setup initdb
  when: check_db_output.rc != 0 

- name: start postgres
  service:
    name: postgresql.service
    enabled: yes
    state: started
